'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.17929
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    '-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    '''<summary>
    '''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Public Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("CharImport_Test.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property empty() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("empty", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die effectid;effectname
        '''1;Felsbeißer 3
        '''2;Frostbrand
        '''3;Flammenzunge 3
        '''4;Flammenzunge 2
        '''5;Flammenzunge
        '''6;Felsbeißer 2
        '''7;Tödliches Gift
        '''8;Tödliches Gift II
        '''9;Gift (15 Schaden)
        '''10;Gift (20 Schaden)
        '''11;Gift (25 Schaden)
        '''12;Frostbrand 2
        '''13;Geschärft (+3 Schaden)
        '''14;Geschärft (+4 Schaden)
        '''15;Verstärkt (+8 Rüstung)
        '''16;Verstärkt (+16 Rüstung)
        '''17;Verstärkt (+24 Rüstung)
        '''18;Verstärkt (+32 Rüstung)
        '''19;Beschwert (+2 Schaden)
        '''20;Beschwert (+3 Schaden)
        '''21;Beschwert (+4 Schaden)
        '''22;Verkrüppelungsgift
        '''23; [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Public ReadOnly Property enchant_name_de() As String
            Get
                Return ResourceManager.GetString("enchant_name_de", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die effectid;effectname
        '''1;Rockbiter 3
        '''2;Frostbrand
        '''3;Flametongue 3
        '''4;Flametongue 2
        '''5;Flametongue
        '''6;Rockbiter 2
        '''7;Deadly Poison
        '''8;Deadly Poison II
        '''9;Poison (15 Dmg)
        '''10;Poison (20 Dmg)
        '''11;Poison (25 Dmg)
        '''12;Frostbrand 2
        '''13;Sharpened (+3 Damage)
        '''14;Sharpened (+4 Damage)
        '''15;Reinforced (+8 Armor)
        '''16;Reinforced (+16 Armor)
        '''17;Reinforced (+24 Armor)
        '''18;Reinforced (+32 Armor)
        '''19;Weighted (+2 Damage)
        '''20;Weighted (+3 Damage)
        '''21;Weighted (+4 Damage)
        '''22;Crippling Poison
        '''23;Mind-numbing Poison II
        '''24; [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Public ReadOnly Property enchant_name_en() As String
            Get
                Return ResourceManager.GetString("enchant_name_en", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die long:long:
        '''77154;4677;xxxx
        '''77144;4686;xxxx
        '''77143;4685;xxxx
        '''77142;4684;xxxx
        '''77141;4683;xxxx
        '''77140;4682;xxxx
        '''77139;4681;xxxx
        '''77138;4680;xxxx
        '''77137;4679;xxxx
        '''77136;4678;xxxx
        '''77134;4676;xxxx
        '''77133;4675;xxxx
        '''77132;4674;xxxx
        '''77131;4673;xxxx
        '''77130;4672;xxxx
        '''71883;4333;xxxx
        '''71882;4332;xxxx
        '''71881;4331;xxxx
        '''71880;4330;xxxx
        '''71879;4329;xxxx
        '''71878;4338;xxxx
        '''71877;4337;xxxx
        '''71876;4336;xxxx
        '''71875;4335;xxxx
        '''71874;4334;xxxx
        '''71873;4328;xxxx
        '''71872;4327;xxxx
        '''71871;4326;xxxx
        '''71870;4325;xxxx
        '''71869;4 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Public ReadOnly Property GEM_ID_cata() As String
            Get
                Return ResourceManager.GetString("GEM_ID_cata", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die long;long;
        '''4677;77154;xxxx
        '''4686;77144;xxxx
        '''4685;77143;xxxx
        '''4684;77142;xxxx
        '''4683;77141;xxxx
        '''4682;77140;xxxx
        '''4681;77139;xxxx
        '''4680;77138;xxxx
        '''4679;77137;xxxx
        '''4678;77136;xxxx
        '''4676;77134;xxxx
        '''4675;77133;xxxx
        '''4674;77132;xxxx
        '''4673;77131;xxxx
        '''4672;77130;xxxx
        '''4333;71883;xxxx
        '''4332;71882;xxxx
        '''4331;71881;xxxx
        '''4330;71880;xxxx
        '''4329;71879;xxxx
        '''4338;71878;xxxx
        '''4337;71877;xxxx
        '''4336;71876;xxxx
        '''4335;71875;xxxx
        '''4334;71874;xxxx
        '''4328;71873;xxxx
        '''4327;71872;xxxx
        '''4326;71871;xxxx
        '''4325;71870;xxxx
        '''4324;71 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Public ReadOnly Property GEM_ID_cata2() As String
            Get
                Return ResourceManager.GetString("GEM_ID_cata2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die long;long;
        '''49110;3879;xxxx
        '''45987;3867;xxxx
        '''45883;3866;xxxx
        '''45882;3865;xxxx
        '''45881;3864;xxxx
        '''45880;3863;xxxx
        '''45879;3862;xxxx
        '''45862;3861;xxxx
        '''44089;3805;xxxx
        '''44088;3804;xxxx
        '''44087;3803;xxxx
        '''44084;3802;xxxx
        '''44082;3800;xxxx
        '''44081;3801;xxxx
        '''44078;3799;xxxx
        '''44076;3798;xxxx
        '''44066;3792;xxxx
        '''42702;3750;xxxx
        '''42701;3749;xxxx
        '''42158;3744;xxxx
        '''42157;3743;xxxx
        '''42156;3742;xxxx
        '''42155;3747;xxxx
        '''42154;3746;xxxx
        '''42153;3745;xxxx
        '''42152;3741;xxxx
        '''42151;3740;xxxx
        '''42150;3739;xxxx
        '''42149;3738;xxxx
        '''42148;3 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Public ReadOnly Property GEM_ID_wotlk() As String
            Get
                Return ResourceManager.GetString("GEM_ID_wotlk", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die long;long;
        '''3879;49110;xxxx
        '''3867;45987;xxxx
        '''3866;45883;xxxx
        '''3865;45882;xxxx
        '''3864;45881;xxxx
        '''3863;45880;xxxx
        '''3862;45879;xxxx
        '''3861;45862;xxxx
        '''3805;44089;xxxx
        '''3804;44088;xxxx
        '''3803;44087;xxxx
        '''3802;44084;xxxx
        '''3800;44082;xxxx
        '''3801;44081;xxxx
        '''3799;44078;xxxx
        '''3798;44076;xxxx
        '''3792;44066;xxxx
        '''3750;42702;xxxx
        '''3749;42701;xxxx
        '''3744;42158;xxxx
        '''3743;42157;xxxx
        '''3742;42156;xxxx
        '''3747;42155;xxxx
        '''3746;42154;xxxx
        '''3745;42153;xxxx
        '''3741;42152;xxxx
        '''3740;42151;xxxx
        '''3739;42150;xxxx
        '''3738;42149;xxxx
        '''3737;42 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Public ReadOnly Property GEM_ID_wotlk2() As String
            Get
                Return ResourceManager.GetString("GEM_ID_wotlk2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die Column 1
        '''flags,long,long,long,
        '''0x0,52084,2,3098,
        '''0xA2,12320,21,0,
        '''0x80,12297,22,0,
        '''0x2,46831,61,0,
        '''0x1,52084,81,0,
        '''0x80,52085,82,0,
        '''0x0,0,101,0,
        '''0x40,46487,121,2681,
        '''0x1,54292,141,3115,
        '''0x0,54810,161,3114,
        '''0x0,54811,162,3113,
        '''0x0,54812,163,3312,
        '''0x0,54813,164,3124,
        '''0x0,54815,165,3129,
        '''0x0,54818,166,3112,
        '''0x0,54821,167,3128,
        '''0x0,54824,168,3123,
        '''0x0,54832,169,3121,
        '''0x0,54733,170,3127,
        '''0x0,54743,171,3098,
        '''0x0,54754,172,3125,
        '''0x0,54825,173,3119,
        '''0x0,54826,174,3120,
        '''0x0,54845,175,3117,
        ''' [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Public ReadOnly Property GlyphProperties() As String
            Get
                Return ResourceManager.GetString("GlyphProperties", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &lt;entry&gt;2&lt;/entry&gt;&lt;spell&gt;52084&lt;/spell&gt;&lt;entry2&gt;2&lt;/entry2&gt;&lt;spell2&gt;52084&lt;/spell2&gt;
        '''&lt;entry&gt;21&lt;/entry&gt;&lt;spell&gt;12320&lt;/spell&gt;&lt;entry2&gt;21&lt;/entry2&gt;&lt;spell2&gt;12320&lt;/spell2&gt;
        '''&lt;entry&gt;22&lt;/entry&gt;&lt;spell&gt;12297&lt;/spell&gt;&lt;entry2&gt;22&lt;/entry2&gt;&lt;spell2&gt;12297&lt;/spell2&gt;
        '''&lt;entry&gt;61&lt;/entry&gt;&lt;spell&gt;46831&lt;/spell&gt;&lt;entry2&gt;61&lt;/entry2&gt;&lt;spell2&gt;46831&lt;/spell2&gt;
        '''&lt;entry&gt;81&lt;/entry&gt;&lt;spell&gt;52084&lt;/spell&gt;&lt;entry2&gt;81&lt;/entry2&gt;&lt;spell2&gt;52084&lt;/spell2&gt;
        '''&lt;entry&gt;82&lt;/entry&gt;&lt;spell&gt;52085&lt;/spell&gt;&lt;entry2&gt;82&lt;/entry2&gt;&lt;spell2&gt;52085&lt;/spell2&gt;
        '''&lt;entry&gt;101&lt;/entry&gt;&lt;spell&gt;0&lt;/spell&gt; [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Public ReadOnly Property GlyphProperties_335() As String
            Get
                Return ResourceManager.GetString("GlyphProperties_335", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &lt;entry&gt;161&lt;/entry&gt;&lt;spell&gt;54810&lt;/spell&gt;&lt;entry2&gt;161&lt;/entry2&gt;&lt;spell2&gt;54810&lt;/spell2&gt;
        '''&lt;entry&gt;162&lt;/entry&gt;&lt;spell&gt;54811&lt;/spell&gt;&lt;entry2&gt;162&lt;/entry2&gt;&lt;spell2&gt;54811&lt;/spell2&gt;
        '''&lt;entry&gt;163&lt;/entry&gt;&lt;spell&gt;54812&lt;/spell&gt;&lt;entry2&gt;163&lt;/entry2&gt;&lt;spell2&gt;54812&lt;/spell2&gt;
        '''&lt;entry&gt;164&lt;/entry&gt;&lt;spell&gt;54813&lt;/spell&gt;&lt;entry2&gt;164&lt;/entry2&gt;&lt;spell2&gt;54813&lt;/spell2&gt;
        '''&lt;entry&gt;165&lt;/entry&gt;&lt;spell&gt;54815&lt;/spell&gt;&lt;entry2&gt;165&lt;/entry2&gt;&lt;spell2&gt;54815&lt;/spell2&gt;
        '''&lt;entry&gt;166&lt;/entry&gt;&lt;spell&gt;54818&lt;/spell&gt;&lt;entry2&gt;166&lt;/entry2&gt;&lt;spell2&gt;54818&lt;/spell2&gt;
        '''&lt;entry&gt;167&lt;/entry&gt;&lt;s [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Public ReadOnly Property GlyphProperties_434() As String
            Get
                Return ResourceManager.GetString("GlyphProperties_434", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die itemid;itemname
        '''25;Abgenutztes Kurzschwert
        '''35;Gebogener Stab
        '''36;Abgenutzter Streitkolben
        '''37;Abgenutzte Axt
        '''38;Rekrutenhemd
        '''39;Rekrutenhose
        '''40;Rekrutenstiefel
        '''42;OLDSquire&apos;s Belt
        '''43;Knappenstiefel
        '''44;Knappenhose
        '''45;Knappenhemd
        '''47;Straßenräuberschuhe
        '''48;Straßenräuberhose
        '''49;Straßenräuberhemd
        '''51;Neophytenstiefel
        '''52;Neophytenhose
        '''53;Neophytenhemd
        '''55;Lehrlingsstiefel
        '''56;Lehrlingsrobe
        '''57;Akolythenrobe
        '''59;Akolythenschuhe
        '''60;Mehrlagige Tunika
        '''61;Zwergische Lederhose
        '''79;Zwergische Stoffknieho [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Public ReadOnly Property item_name_de() As String
            Get
                Return ResourceManager.GetString("item_name_de", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die itemid;itemname
        '''17;Martin Fury
        '''25;Worn Shortsword
        '''35;Bent Staff
        '''36;Worn Mace
        '''37;Worn Axe
        '''38;Recruit&apos;s Shirt
        '''39;Recruit&apos;s Pants
        '''40;Recruit&apos;s Boots
        '''43;Squire&apos;s Boots
        '''44;Squire&apos;s Pants
        '''45;Squire&apos;s Shirt
        '''47;Footpad&apos;s Shoes
        '''48;Footpad&apos;s Pants
        '''49;Footpad&apos;s Shirt
        '''51;Neophyte&apos;s Boots
        '''52;Neophyte&apos;s Pants
        '''53;Neophyte&apos;s Shirt
        '''55;Apprentice&apos;s Boots
        '''56;Apprentice&apos;s Robe
        '''57;Acolyte&apos;s Robe
        '''59;Acolyte&apos;s Shoes
        '''60;Layered Tunic
        '''61;Dwarven Leather Pants
        '''79;Dwarven Cloth Britches
        '''80;Soft Fur-Lined Shoe [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Public ReadOnly Property item_name_en() As String
            Get
                Return ResourceManager.GetString("item_name_en", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die yyyyFelsbeißer 3xxxx1qqqq0zzzz
        '''yyyyFrostbrand 1xxxx2qqqq8034zzzz
        '''yyyyFlammenzunge 3xxxx3qqqq15568zzzz
        '''yyyyFlammenzunge 2xxxx4qqqq15567zzzz
        '''yyyyFlammenzunge 1xxxx5qqqq10400zzzz
        '''yyyyFelsbeißer 2xxxx6qqqq0zzzz
        '''yyyyTödliches Giftxxxx7qqqq2818zzzz
        '''yyyyTödliches Gift IIxxxx8qqqq2819zzzz
        '''yyyyGift (15 Schaden)xxxx9qqqq2820zzzz
        '''yyyyGift (20 Schaden)xxxx10qqqq2821zzzz
        '''yyyyGift (25 Schaden)xxxx11qqqq2822zzzz
        '''yyyyFrostbrand 2xxxx12qqqq8037zzzz
        '''yyyyGeschärft (+3 Schaden)xxxx13qqqq0zzzz
        '''yyyyGeschärft (+4 Sch [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Public ReadOnly Property SpellItemEnchantment() As String
            Get
                Return ResourceManager.GetString("SpellItemEnchantment", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die yyyyFelsbeißer 3xxxx1qqqq0zzzz
        '''yyyyFrostbrandxxxx2qqqq8034zzzz
        '''yyyyFlammenzunge 3xxxx3qqqq15568zzzz
        '''yyyyFlammenzunge 2xxxx4qqqq15567zzzz
        '''yyyyFlammenzungexxxx5qqqq10400zzzz
        '''yyyyFelsbeißer 2xxxx6qqqq0zzzz
        '''yyyyTödliches Giftxxxx7qqqq2818zzzz
        '''yyyyTödliches Gift IIxxxx8qqqq2819zzzz
        '''yyyyGift (15 Schaden)xxxx9qqqq2820zzzz
        '''yyyyGift (20 Schaden)xxxx10qqqq2821zzzz
        '''yyyyGift (25 Schaden)xxxx11qqqq2822zzzz
        '''yyyyFrostbrand 2xxxx12qqqq8037zzzz
        '''yyyyGeschärft (+3 Schaden)xxxx13qqqq0zzzz
        '''yyyyGeschärft (+4 Schaden [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Public ReadOnly Property SpellItemEnchantmentCata() As String
            Get
                Return ResourceManager.GetString("SpellItemEnchantmentCata", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die TalentId;Rang1;Rang2;Rang3;Rang4;Rang5
        '''27;11078;11080;0;0;0
        '''1141;18459;18460;54734;0;0
        '''26;11069;12338;12339;12340;12341
        '''34;11119;11120;12846;12847;12848
        '''2212;54747;54749;0;0;0
        '''31;11108;12349;12350;0;0
        '''28;11100;12353;0;0;0
        '''30;11103;12357;12358;0;0
        '''29;11366;0;0;0;0
        '''23;11083;12351;0;0;0
        '''25;11095;12872;12873;0;0
        '''24;11094;13043;0;0;0
        '''1639;29074;29075;29076;0;0
        '''1730;31638;31639;31640;0;0
        '''33;11115;11367;11368;0;0
        '''32;11113;0;0;0;0
        '''1731;31641;31642;0;0;0
        '''35;11124;12378;12398;12399;12400
        '''1733;34293 [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Public ReadOnly Property Talent() As String
            Get
                Return ResourceManager.GetString("Talent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die str;long;
        '''Felsbeißer 3;1;xxxx
        '''Frostbrand;2;xxxx
        '''Flammenzunge 3;3;xxxx
        '''Flammenzunge 2;4;xxxx
        '''Flammenzunge;5;xxxx
        '''Felsbeißer 2;6;xxxx
        '''Tödliches Gift;7;xxxx
        '''Tödliches Gift II;8;xxxx
        '''Gift (15 Schaden);9;xxxx
        '''Gift (20 Schaden);10;xxxx
        '''Gift (25 Schaden);11;xxxx
        '''Frostbrand 2;12;xxxx
        '''Geschärft (+3 Schaden);13;xxxx
        '''Geschärft (+4 Schaden);14;xxxx
        '''Verstärkt (+8 Rüstung);15;xxxx
        '''Verstärkt (+16 Rüstung);16;xxxx
        '''Verstärkt (+24 Rüstung);17;xxxx
        '''Verstärkt (+32 Rüstung);18;xxxx
        '''Beschwert (+2 Schaden);19;x [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Public ReadOnly Property VZ_ID_cata() As String
            Get
                Return ResourceManager.GetString("VZ_ID_cata", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die long;str;
        '''1;Felsbeißer 3;xxxx
        '''2;Frostbrand;xxxx
        '''3;Flammenzunge 3;xxxx
        '''4;Flammenzunge 2;xxxx
        '''5;Flammenzunge;xxxx
        '''6;Felsbeißer 2;xxxx
        '''7;Tödliches Gift;xxxx
        '''8;Tödliches Gift II;xxxx
        '''9;Gift (15 Schaden);xxxx
        '''10;Gift (20 Schaden);xxxx
        '''11;Gift (25 Schaden);xxxx
        '''12;Frostbrand 2;xxxx
        '''13;Geschärft (+3 Schaden);xxxx
        '''14;Geschärft (+4 Schaden);xxxx
        '''15;Verstärkt (+8 Rüstung);xxxx
        '''16;Verstärkt (+16 Rüstung);xxxx
        '''17;Verstärkt (+24 Rüstung);xxxx
        '''18;Verstärkt (+32 Rüstung);xxxx
        '''19;Beschwert (+2 Schaden);x [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Public ReadOnly Property VZ_ID_cata2() As String
            Get
                Return ResourceManager.GetString("VZ_ID_cata2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die str;long;
        '''Felsbeißer 3;1;xxxx
        '''Frostbrand 1;2;xxxx
        '''Flammenzunge 3;3;xxxx
        '''Flammenzunge 2;4;xxxx
        '''Flammenzunge 1;5;xxxx
        '''Felsbeißer 2;6;xxxx
        '''Tödliches Gift;7;xxxx
        '''Tödliches Gift II;8;xxxx
        '''Gift (15 Schaden);9;xxxx
        '''Gift (20 Schaden);10;xxxx
        '''Gift (25 Schaden);11;xxxx
        '''Frostbrand 2;12;xxxx
        '''Geschärft (+3 Schaden);13;xxxx
        '''Geschärft (+4 Schaden);14;xxxx
        '''Verstärkt (+8 Rüstung);15;xxxx
        '''Verstärkt (+16 Rüstung);16;xxxx
        '''Verstärkt (+24 Rüstung);17;xxxx
        '''Verstärkt (+32 Rüstung);18;xxxx
        '''Beschwert (+2 Schaden); [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Public ReadOnly Property VZ_ID_wotlk() As String
            Get
                Return ResourceManager.GetString("VZ_ID_wotlk", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die long;str;
        '''1;Felsbeißer 3;xxxx
        '''2;Frostbrand 1;xxxx
        '''3;Flammenzunge 3;xxxx
        '''4;Flammenzunge 2;xxxx
        '''5;Flammenzunge 1;xxxx
        '''6;Felsbeißer 2;xxxx
        '''7;Tödliches Gift;xxxx
        '''8;Tödliches Gift II;xxxx
        '''9;Gift (15 Schaden);xxxx
        '''10;Gift (20 Schaden);xxxx
        '''11;Gift (25 Schaden);xxxx
        '''12;Frostbrand 2;xxxx
        '''13;Geschärft (+3 Schaden);xxxx
        '''14;Geschärft (+4 Schaden);xxxx
        '''15;Verstärkt (+8 Rüstung);xxxx
        '''16;Verstärkt (+16 Rüstung);xxxx
        '''17;Verstärkt (+24 Rüstung);xxxx
        '''18;Verstärkt (+32 Rüstung);xxxx
        '''19;Beschwert (+2 Schade [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Public ReadOnly Property VZ_ID_wotlk2() As String
            Get
                Return ResourceManager.GetString("VZ_ID_wotlk2", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
